services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7686084591:AAGwDMSgj0bjOCf0fgyypVM6wVBehPY-icA
      - key: OPENROUTER_API_KEY
        value: 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
environment:
  - PORT=8080
